services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    tty: true
    privileged: true
    volumes:
      - ./device_management:/code/device_management
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - MQTT_BROKER=mqttbroker
      - MQTT_PORT=1883
  mqttbroker:
    image: eclipse-mosquitto
    container_name: mqttbroker
    ports:
      - '30883:1883' #default mqtt port
      - '9001:9001' #default mqtt port for websockets
    volumes:
      - ./configs/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - mqtt_data:/mosquitto/data:rw
      - mqtt_log:/mosquitto/log:rw
    networks:
      - mqttbroker_network
      - default

volumes:
  db_data:
  mqtt_data:
  mqtt_log:

networks:
  mqttbroker_network:
    name: mqttbroker_network
    driver: bridge
    