apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size as per your requirement

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi  # Adjust the size as per your requirement
