# Generated by Django 3.2.25 on 2024-05-17 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_value', models.FloatField()),
                ('comparison_type', models.CharField(choices=[('=', 'Equal To'), ('<', 'Less Than'), ('>', 'Greater Than')], max_length=1)),
                ('command', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_actions', to='devices.sensor')),
                ('recipient_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_actions', to='devices.sensor')),
            ],
        ),
    ]
